### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by frost4869** [justdmitry/PassKitHelper#12]
Is there a way to add a language directory for localization ?
Ex: `en.lproj/pass.strings`

Doc: https://developer.apple.com/documentation/walletpasses/creating_the_source_for_a_pass?changes=_2_8_8

**Comment by justdmitry** [comment]
Sure.

Use `PassPackageBuilder.AddFile` and provide `en.lproj/pass.strings` as name.

**Comment by frost4869** [comment]
Worked like a charm. Thanks
