### ISSUE TITLE
Any guidance on updating?

### ISSUE THREAD

**Issue by george-karma** [justdmitry/PassKitHelper#13]
I have everything setup as in the readme but the apple server/device isn't hitting the RegisterDeviceAsync method. Should a webservice url be provided in the pass? And how to do this?

**Comment by justdmitry** [comment]
Yes, you need to put some data into pass:
```
pass.WebService
           .WebServiceURL("https://your-server/path")
           .AuthenticationToken("some secret string you can verify it's not hacker")                    
```

**Comment by george-karma** [comment]
Does the WebServiceURL have to be any specific path since i did add the callbacks for the passkit helper?

**Comment by george-karma** [comment]
@justdmitry do you have an example for this? :)

**Comment by justdmitry** [comment]
If your server URL is `https://example.com` and you followed readme 3.2 and called `app.UsePassKitMiddleware("/callbacks/passkit");` in Startup then you should set in your passes `.WebServiceURL("https://example.com/callbacks/passkit")`

**Comment by george-karma** [comment]
Will give it a quick try now thank you

**Comment by george-karma** [comment]
Still cant figure it out, seems like apple is never calling the callback

**Comment by justdmitry** [comment]
Calls my server in all 5 or 7 projects. Are you sure you added public URL in cards?

**Comment by george-karma** [comment]
Tried adding a remote server and local server, just doesn't call the callback. Do you have any public projects you implemented this in, i might be missing something?

**Comment by justdmitry** [comment]
No, sorry, all commercial.

But it usually works without any problems.
* I have `WebserviceBasePath` in appsettings with value like `https://myserver.net/callbacks/passkit/`
* I have `app.UsePassKitMiddleware("/callbacks/passkit");` in my startup
* I put `WebserviceBasePath` value into `pass.WebService.WebServiceURL`

1) Do you have HTTPS on your server? Don't remember about Apple, but some other providers require.
2) Never thought about it, but... do you have "/" at end of your value in WebServiceURL ?

**Comment by george-karma** [comment]
Didnt use "/" at the end of the WebServiceURL. The Get GetAssociatedPassesAsync method was not quering my CRM properly. Thanks for your help on this @justdmitry . Hope you have a good day : )
