### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by johantiger** [justdmitry/PassKitHelper#15]
Hi, I can't find any options to pass in localization options to the creation of cards. Is that a possibility? 
Love the package! Thanks!

**Comment by justdmitry** [comment]
Hi,
As far as I remember, localization is additional file with localized strings. You should build it in-memory (StreamWriter/StringWriter) and add it to package with `passPackage.AddFile()`. 
But I didn't build international passes yet, so please describe what exact problem you have with that scenario.

**Comment by johantiger** [comment]
Thanks for your quick answer, and you are partially right, if I read [this](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html) correctly, each supported language needs it's own folder, so a `sv.lproj` folder for my Swedish strings and so on.

**Comment by johantiger** [comment]
So sorry @justdmitry , I looked through the closed issues now, you already had posted about this. Have a great day, thanks!
