### ISSUE TITLE
Push notification text is the same when two updates occur 

### ISSUE THREAD

**Issue by DboukAli98** [justdmitry/PassKitHelper#18]
Hello @justdmitry  , 
Thanks for this amazing library , I successfully implemented the Update Pass and send push notification features .
But I am facing an issue when I update two fields in a pass , the Push Notification Text I receive is always the same "Store Card Changed" , but when only one field is updated , the Push Notification text successfully shows the changed field message .
So I want when multiple fields got updates to show their change messages also.
Can you please help or guide me to fix this problem .
Thanks in advance !

**Comment by justdmitry** [comment]
You can add `ChangeMessage` property to any field, and this text will be displayed when value of this field will change (compared to previous pass instance on user's device).

This text must include `%@` placeholder for actual (new) field value, more details [in docs](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/FieldDictionary.html#//apple_ref/doc/uid/TP40012026-CH4-SW5).

I'm not 100% sure, but I remember that when I change several fields in new pass, but only one of them have non-empty "changeMessage" - only this message is shown on lock screen notification. Don't know what will happen if several changed fields will have "change message", never tried this scenario.

**Comment by DboukAli98** [comment]
Okay thanks
