### ISSUE TITLE
PassKit for google pay passes

### ISSUE THREAD

**Issue by dolphinsd** [justdmitry/PassKitHelper#2]
Dmitry, have your considered to add support for google pay passes. Apple and Google seems to be very similar, like they copied each other, let me know vkroutik sobachka gmail tochka com

Spasibo, Vlad.

**Comment by justdmitry** [comment]
As far as I know Google passes are very different - passed are pushed to Google server and special link is built for user to add this pass to his wallet. Also, I don’t know about any webhooks from G servers back to app.

If you know G docs with similar (to PassKit) features - give me know about them plz

**Comment by dolphinsd** [comment]
Here are 2 good links. From what I read, it very much the same:
https://developers.google.com/pay/passes/support/libraries#libraries
and
https://github.com/google-pay/passes-rest-samples/tree/master/csharp

Maybe adding a factory for which wallet to use?!

**Comment by justdmitry** [comment]
No, its not the same.
I had read that docs (and implemented Google Passes in one app with them). G Passes work in absolutely different way. No callbacks. No any file for client to download. Only push some data to G server and prepare link for client to get pass from G server. Nothing "like" Apple Passes (from developer PoV).
