### ISSUE TITLE
Not receiving push notification

### ISSUE THREAD

**Issue by faheem-riaz** [justdmitry/PassKitHelper#22]
1. Created a pass
2. Send it to ios device and added the pass. Got the logs and device pushToken.
3. I updated the pass from the code like change the foreground color and expiry date. 
4. Send the notification to the pushToken I receive in step 2.
5. Webservice is getting triggered but I did not get notification on my iOS device and also pass is not updated.

**Comment by justdmitry** [comment]
At step (5): does pass change on your iOS device? Or you are waiting for some onscreen popup notifications?

**Comment by justdmitry** [comment]
What types of calls you receive at step (5)? As far as I remember, first you will receive GetAssociatedPasses() with last-timestamp and you should response with list of passes that were updated since that time, and after that you'll receive GetPass() for each updated pass.

**Comment by faheem-riaz** [comment]
@justdmitry  After digging in I found out I have missed this endpoint
![image](https://user-images.githubusercontent.com/42313806/236801295-ec32a325-f56d-4ff9-a32a-8a69c219f9fb.png)
After adding it My pass is updated but I am not getting Any notification. I am creating a coupon and I change the expire and its working. but still no notification received.

**Comment by justdmitry** [comment]
How could you miss one endpoint while implementing `IPassKitService`???

And what notifications you talk about now - about onscreen popups? IIRC it shows only when you change values of fields displayed on pass front face.
