### ISSUE TITLE
Missing steps on how to install the pass

### ISSUE THREAD

**Issue by dolphinsd** [justdmitry/PassKitHelper#3]
I have used the demo app to create a pass! Yeah. I can email it to myself and open on iPhone.

How do I install it on the phone with a link? Is there way to display it in the web page as well? Or generate barcode?

**Comment by justdmitry** [comment]
ASP.Net Core (and any other frameworks) allow your to send binary file from server in respond to user request.

**Comment by dolphinsd** [comment]
Thanks for insight, yes, its one of the way, including emails.
