### ISSUE TITLE
is there way to display barcode as an image

### ISSUE THREAD

**Issue by dolphinsd** [justdmitry/PassKitHelper#4]
Is there a built in way to get a barcode out of the pass as an image? or 3rd party library is required?

**Comment by justdmitry** [comment]
Pass is a ZIP file which contain only barcode value string. Image is generated by iOS device while parsing/displaying pass. If you want to generate barcode image from a string - you don’t need a PassKit for this

**Comment by dolphinsd** [comment]
@justdmitry , thanks, I found a few 3rd party libraries to generate image from a string.
