### ISSUE TITLE
push notification does not work

### ISSUE THREAD

**Issue by dolphinsd** [justdmitry/PassKitHelper#5]
It fails, as apple requires https/2 for 13+ devices.

this still works:
https://github.com/tomasmcguinness/dotnet-passbook/blob/56a149e955b4f8acb26b8c69f9e7058ddb047b09/Passbook.Sample.Web/Services/SendEmptyPushNotification.cs

**Comment by justdmitry** [comment]
Fixed in v3.0.1,  works for me in .netcore 3.1 and 5.0.
